---
- name: IPTABLES OFF
  command: "iptables -F"

- name: firewall enabling
  firewalld:
    permanent: yes
    immediate: yes
    state: disabled
    port: 80/tcp 

- name: SELINUX
  command: sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config 
