---
- name: enable rabbitmq plugins
  rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_tracing,rabbitmq_federation
    state: enabled

- name: Add Admin User
  rabbitmq_user:
    user: "{{ item }}"
    password: "{{ rabbitmq_admin_password }}"
    tags: administrator,{{item}}
    vhost: /
    configure_priv: .*
    write_priv: .*
    read_priv: .*
    state: present
  with_items:
  - "{{ rabbitmq_admin_user }}"

- name: HAPolicy Updated
  command: rabbitmqctl set_policy ha-all "" '{"ha-mode":"all","ha-sync-mode":"automatic"}'
  
