---
# defaults file for java-role

java_home: ""

#packages variables for FreeBSD 
#other Java version options are following. [
#[openjdk6, openjdk8]

FreeBSD_package: openjdk

#packages variables for RedHat distribution
#Other Java versions for RedHat are following
#[java-1.6.0-openjdk, java-1.7.0-openjdk ]

RedHat_package: java-1.8.0-openjdk

#packages variables for Debian distribution
#Other Java versions for Debian are following
#[java, openjdk-9-jdk, openjdk-11-jdk]

Debian_package: openjdk-8-jdk